<Project Sdk="Godot.NET.Sdk/4.6.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>UntitledStackerGame</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="code\gdscript\match_scene.gd" />
    <Content Include="code\gdscript\match_scene.gd.uid" />
  </ItemGroup>
</Project>